### PR TITLE
Open to new maintainer

### PR DESCRIPTION
**Pull request by sandstrom**
This project is awesome and it would be sad to see it slowly fade away.

Perhaps there is someone qualified that could take over? (would love to but I don't have bandwidth right now)

You could always do a short trial-period: ask them to answer 10 issues and 10 pull requests, and see if they seem qualified.

### CODE REVIEW

**Comment by sandstrom** [comment]
friendly ping @almossawi @hamilton @wlach 😄

**Comment by jens-ox** [comment]
Hi! Feel free to check out my PR (#929) if you're interested in a modernized version of MetricsGraphics.

**Comment by wlach** [comment]
@sandstrom Unfortunately as I just mentioned in #929, I don't really have time to evaluate new contributions to metrics graphics. However, if someone wants to fork the library and publish under their username on npm, I'd be happy to link to them from README -- after some time and after a track record has been established, we could consider transferring over the organization.

**Comment by sandstrom** [comment]
@wlach I understand the hesitation. However, in this case @jens-ox hasn't asked for repo access or transfer, he's only spend considerable time updating the codebase. Those are good signs! 

Sort of like recruiting to CIA or other sensitive jobs. If people apply for them you should always be wary of moles etc, but if **you** have recruited them, that risk is extremely low. Obviously a previously good actor could "turn bad" afterwards, but that risk exist for the current repo + owner too 😉

Still, obviously it makes sense for you to wait a while and see + totally your call.

But there is also the tradeoff of keeping this awesome(!) repo alive + keeping momentum vs. the event-stream-incident risk.

*(also commented in https://github.com/metricsgraphics/metrics-graphics/pull/929#issuecomment-590265940)*

**Pull request closed without merging**
