### PR TITLE
create a corresponding extent in the overview plot when zooming

### PR DESCRIPTION
**Pull request by cnwangjie**

### CODE REVIEW

**Comment by cnwangjie** [comment]
For the first problem, I previously referred to the flotcharts and considered some enhanced brushing and zooming features. so I specifically judged this situation. I've changed it in the new commit.
And main plot can zoom correctly after brushing in overview plot in my test. Could you try out the example on the examples page? Can it work correctly?

**Comment by wlach** [comment]
@cnwangjie this works much better, thank you! the only thing that still seems a little odd is that the brushing on the overview plot still doesn't seem to work unless I am over a line? I am not sure if that is due to the overview plot code or that the brushing in the example only works on the x axis, but it's a bit frustrating to use as-is. Do you know what I mean? If not I can try to create a screencast example.

**Comment by wlach** [comment]
@cnwangjie so in this video, I'm trying to initiate a brush event by clicking on a point on the graph and dragging, but it doesn't work. It's only when I click on the line itself and start dragging that it works.

struggling to drag

Hopefully that makes sense?

**Comment by cnwangjie** [comment]
@wlach Thank you. I think I understand. I spent some time looking for the cause of this problem.
To avoid adding more element. The target element of event listener is same as the mouseover event. The distance between the top of this element and the top of the svg element is set to `args.buffer + args.title_y_position`. Because the default value of title_y_position is 10, buffer is 8 and I set top as 0. So 18 pixels from the top of the svg cannot trigger this event.

I will modify the example later, and I found that `title_y_position` is not in the list of options page.

**Comment by cnwangjie** [comment]
@wlach I found that many types of charts will take calculation with `title_y_position`. But they call `chart_title` when init. So I suggest setting `title_y_position` to zero if chart without title in this function. I think this is a clean solution for this problem.

**Comment by cnwangjie** [comment]
@wlach Ok, I've changed it. I am a bit worried that this will cause too many places to make same changes. It may cause repetition and easy to miss.

**Pull request merged**
