### PR TITLE
Modernizing MetricsGraphics

### PR DESCRIPTION
**Pull request by jens-ox**
Hi all!
First of all, this PR is currently not intended to be merged. I'm still working on it (and it will take some while until a stable state is reached). I just wanted some input.

As @wlach pointed out in [his blogpost from September 2019](https://wlach.github.io/blog/2019/09/metrics-graphics-stepping-back-for-a-while/), MetricsGraphics is currently unmaintained.
Also, there are some general problems with the current state of the codebase:

* it is written in "old" JavaScript, lots of code can be heavily simplified (see also #902 )
* "old" tooling is used (jshint et al). Both the codebase and the artifacts could be optimized using things like Webpack and ESLint (see also #860, #903)
* testing is in bad shape (see #845)

Because MetricsGraphics was one of the things that really got me into data visualization, I started modernizing the codebase on [my fork](https://github.com/jens-ox/metrics-graphics). The following things are done:

* All dependencies updated
* renovated gulp tasks
* Migrated to ESLint
* Using Webpack to build umd2 modules
* Correctly re-build on changes, both library and examples
* Correctly included the styling files (which were kind of broken on master)

The next steps are:
* untangle remaining side-effects, isolate things like axes and lines in classes
* split up `MG.data_graphic` into multiple classes, one per chart type
* write new tests, document changes to the APIs
* make sure that no functionality of the old version is lost :relaxed: 

These changes are obviously breaking. An example chart changes from

```js
    MG.data_graphic({
        title: "UFO Sightings",
        description: "Yearly UFO sightings from the year 1945 to 2010.",
        data: data,
        width: 650,
        height: 150,
        target: '#ufo-sightings',
        x_accessor: 'year',
        y_accessor: 'sightings',
        markers: [{'year': 1964, 'label': '"The Creeping Terror" released'}]
    })
```

to

```js
    new LineChart({
        data,
        width: 600,
        height: 200,
        target: '#ufo-sightings',
        xAccessor: 'year',
        yAccessor: 'sightings',
        markers: [{'year': 1964, 'label': '"The Creeping Terror" released'}]
    })
```

My main question is: Is there any interest in such a breaking overhaul of the library? If there is, great! If not, I'll continue working on my own fork.

### CODE REVIEW

**Comment by jens-ox** [comment]
Also, some ideas for the future:
* add TypeScript type annotations
* maybe expose charts through LitElement as web components for easy use in web frameworks like Vue and React

**Comment by wlach** [comment]
Hi @jens-ox! This looks cool in outline, I was in the middle of a similar refactoring when I gave up on the project.

Unfortunately I don't really have time to properly review this and the [event stream incident](https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident ) has made me a bit hesistant to transfer repositories. I think what I'd recommend is pushing this code to a fork and publishing to npm under your username if you want to continue-- I'd be happy to link to you from the repository's README. After a bit of time and a few releases, I would be happy to 
consider transferring the metrics graphics domain + organization over to you.

As suhc, I'm going to close this request, but thanks for looking into this!

Incidentally, @hamilton has been working on a new [svelte](https://svelte.dev/)-based data graphics library (not quite ready to be announced), I think he has envisioned an API similar to what you came up with.

**Comment by jens-ox** [comment]
Hi @wlach! Thanks for getting back. I'll try finishing the refactoring up by next weekend.

**Comment by sandstrom** [comment]
@jens-ox Awesome work! All of this sounds awesome! 💯 

@wlach I understand the hesitation. However, in this case @jens-ox hasn't asked for repo access or transfer, he's only spend considerable time updating the codebase. Those are good signs! 

Sort of like recruiting to CIA or other sensitive jobs. If people apply for them you should always be wary of moles etc, but if **you** have recruited them, that risk is extremely low. Obviously a previously good actor could "turn bad" afterwards, but that risk exist for the current repo + owner too 😉

Still, obviously it makes sense for you to wait a while and see + totally your call.

But there is also the tradeoff of keeping this awesome(!) repo alive + keeping momentum vs. the event-stream-incident risk.

**Comment by jens-ox** [comment]
Thanks for the kind words @sandstrom. I completely get your points @wlach, my intention was not to have the org moved over to me when I opened the PR :sweat_smile:

I started adding some progress info to my fork's readme.

**Comment by jens-ox** [comment]
The base elements are more or less done, here is an UFO chart:

Selection_008

The next steps will be to set up a Lerna monorepo to correctly separate the example stuff and the actual library. Maybe use Preact instead of raw html for the example pages.

**Comment by wlach** [comment]
Awesome! Let me know when you're ready and I will update the README to point to your work.

**Comment by jens-ox** [comment]
The move to a monorepo is completed, a new Preact example site is set up (although it's currently quite empty):

screely-1582990770792

The site should be on [https://affectionate-benz-6e3cf9.netlify.com/](https://affectionate-benz-6e3cf9.netlify.com/).

The first publish to NPM is also done (package `mg2`). I think that all weird steps are done for now -- if you want, you can link the fork in the readme ☺️

**Comment by jens-ox** [comment]
Just bumped the version to 0.1.1. All line chart types should work™ 😅 
I'll try porting most of the remaining stuff tomorrow.
See the examples on the page: https://affectionate-benz-6e3cf9.netlify.com/lines/

**Comment by sandstrom** [comment]
@jens-ox Commenting here, since issues on your fork is disabled.

I'd vote for using something other than `useEuropeanHours` to indicate 24-hour clock. I'd also vote for it to be the default behaviour. Perhaps `twelveHourClock` or `useTwelveHours` 😄 

***

The 24-hour clock is used by a vast majority of all countries, and also by a majority of the global population. It's basically only the US + a handful of countries that used to be British colonies that use it. For example, on both Windows and macOS the 24h clock is the default, and the 12-hour clock is only enabled for a select few countries.

So the terms "European time" or "Military time" only make sense from an insular, American perspective.

https://en.wikipedia.org/wiki/24-hour_clock

**Comment by jens-ox** [comment]
Hi! Creating issues is not possible on forks. 24-hour default makes sense.

**Comment by wlach** [comment]
@jens-ox awesome work! I linked to the fork in the README: https://github.com/metricsgraphics/metrics-graphics/blob/master/README.md

Please keep us updated with how it's going, this is great.

**Comment by sandstrom** [comment]
Agree with the previous speaker, this is awesome! I've checked out the demo page, looks very promising!

This library is so beautifully designed, just the way I think statistics should be presented, so I'm  happy to see the awesome work you're doing @jens-ox !

**Comment by jens-ox** [comment]
Thanks all for the kind words! 😊 
As the fork is a fork, no issues can be created. Therefore, I created a project: https://github.com/jens-ox/metrics-graphics/projects/1

The next steps will be to finish up all base functionality (which is already mostly done for line charts):

- rugs for scatter charts
- multi-dimensional scatter charts (i.e. multiple colors)
- histograms

After that, I'd like to implement a new chart type, ideally a non-cartesian one. The reason behind this is that charts currently extend the `AbstractChart` class. I'd like to convert `AbstractChart` to `CartesianChart` which extends a new `AbstractChart` class (responsible for mounting stuff and setting up the sizes correctly).
This would improve the code base and assure that more diverse chart types can be implemented in the future.

Any thoughts on this? Or ideas what types of charts could/should be added next?

**Comment by sandstrom** [comment]
Awesome! 💯 

Yeah, a CartesianChart sounds like a good idea (I don't know the code base well enough to have a strong opinion on this though).

A few more ideas (though don't be to influenced by this, just some thoughts):

- Are there any smaller adjustments we could make to the website, to highlight that it's still maintained and to drive adoption + discoverability? I don't know much about github pages, but here are some examples from other projects: https://github.com/collections/github-pages-examples I think the current website is really good though, so doesn't have to be any major change. But perhaps dropping the "fork on github" badge, it looks a bit dated, and include some timestamp or similar that indicate the the project is still alive. You'd probably need access to this repo (at least the gh-pages branch) to updated it though.

- Perhaps you could contact some of the forks people, and let them know about your fork and whether they'd like to contribute? (for example https://github.com/cnwangjie/metrics-graphics/commit/78dfa89a1a44b9f73f51aba9e39d959d8ff6eecf)

- Could also do some issue gardening on this repo? I have some snippets below. But basically go through issues and copy-paste some pre-written snippets for most issues. Primarily to close issues that are irrelevant etc., but can also help gather more contributors to the project + mention the new fork. That would also be useful if your fork is later moved into this repo.
    
    For example this is an issue more suited for stackoverflow: https://github.com/metricsgraphics/metrics-graphics/issues/909

- Could add a list of ideas to your fork readme, so that people get ideas of things that could improve. Basically a list of "here are some things that could be useful, feel free to dig in". Could also be a meta-issue linked from readme, with an inline checklist of individual things.

- Plugins to popular frameworks such as React/Ember/Vue could help drive adoption. Since this library is lightweight it's well suited for integration into some of the others.

- Perhaps we could edit the D3 wiki and add this as a plugin (https://github.com/d3/d3/wiki/Plugins)

- A more "selling" readme may be a good idea. Ember recently updated their readme to make it more selling. I think that's a good example. [before](https://github.com/emberjs/ember.js/blob/aa58644915c37fd7cd9e82926e68354fe8bcbaef/README.md) -> [after](https://github.com/emberjs/ember.js/blob/master/README.md)

- Could also ask @wlach if he has ideas! 

- Could also ping earlier contributors to this project and see if they have any input.

***


```
# for question better suited for stackoverflow
Hello & thanks for opening an issue on this repo. Since this is an open-source project it relies on voluntary contributions to advance.

Is this an issue with the code itself, or a general question? For general questions [Stackoverflow](https://stackoverflow.com/) is better than Github.

I'm closing this now, but I'm willing to reopen if there is an actual code issue. If so, steps to reproduce (and ideally a failing test-case) is a good start.

Also, this work is currently progressing in this fork (https://github.com/jens-ox/metrics-graphics) so feel free to jump-in there and have a look.
```

```
# feature requests
Hello & thanks for opening an issue on this repo. Since this is an open-source project it relies on voluntary contributions to advance.

I'm working on a fork, which will probably be merged into this repo at some point. I've updated the code base to use better tooling, such as linters and babel, and rewritten most of the code for modern Javascript. If you'd like to help out, feel free to ping me or open an issue/pr against my repo with suggestions on things to improve.
```

**Comment by jens-ox** [comment]
> Plugins to popular frameworks such as React/Ember/Vue could help drive adoption. Since this library is lightweight it's well suited for integration into some of the others.

Yes, that's a good idea! I'd like to do that in the long run, though, as using it in a framework is already possible (although not that seamless). Also, I think the nicest approach would be to use Web Components for this, so that no custom bindings need to be implemented on a per-framework basis 😅

**Comment by jens-ox** [comment]
> Partly related to the point above, perhaps bump to d3 v5? I think people in general like projects that "feel up to date".
In order to reduce bundle size, the fork directly uses the relevant d3 submodules (like `d3-array`).

**Comment by jens-ox** [comment]
After some turbulent days, I've just updated the mouseover handling to support aggregated mouseovers (which now uses [d3-delaunay](https://github.com/d3/d3-delaunay) for triangulation).
Tomorrow, I'll add rugs to scatter charts.

As I'm forced to take holidays due to the current situation, I'll have lots of time to work on metrics-graphics :blush:

**Comment by sandstrom** [comment]
@jens-ox Sounds awesome! 

Great that the corona epidemic is bringing some good things with it!

**Comment by jens-ox** [comment]
Hi! Multi-categorical scatter charts together with some improvements are done. Next up:

- rugs for scatter charts
- histogram charts

Re your points @sandstrom:
- I don't know about the D3 plugins list, I don't really think of MG as a D3 plugin.
- I will update the README, but having good documentation first is important imho. So the next non-coding ToDos are:
  - write good documentation
  - update README

**Comment by sandstrom** [comment]
The new scatter charts looks beautiful! 💯 

- Good point about it not being a plugin, I agree. I was just thinking that links would help with discoverability. Perhaps there are other places we could have it listed.

One small idea about the multiple lines with rollover:

```js
let dateFormatter = new Intl.DateTimeFormat('de');

new LineChart({
  data: fakeUsers2.map(fakeArray => fakeArray.map(fakeEntry => ({
    ...fakeEntry,
    date: dateFormatter.format(new Date(fakeEntry.date)),
  }))),
  width: 600,
  height: 200,
  target: '#fakeUsers2',
  xAccessor: 'date',
  yAccessor: 'value',
  legend: ['Line 1', 'Line 2', 'Line 3'],
  legendTarget: '#fakeUsers2Legend'
})
```

It would format them as "2014.02.03" instead of "Mon Feb 03 2014 01:00:00 GMT+0100 (Central European Standard Time)". Easier to read if it's shorter.

But it's just a demo so doesn't matter that much.

Could also do something like this: `(new Date(fakeEntry.date)).toISOString().split('T')[0];` // 2014-02-03

**Comment by jens-ox** [comment]
Rugs are done. I'll start working on histograms now. After that, it's time to write documentation and a good readme. First "real" version will be done soon :blush:

**Comment by sandstrom** [comment]
@jens-ox Looks great! 💯

**Comment by jens-ox** [comment]
First version of histograms are implemented, now it's time to write some documentation and README 😊

**Comment by sandstrom** [comment]
Awesome 🚀 

rocket-landing

**Comment by jens-ox** [comment]
All code is now documented and the last bits of unused code are removed. Also, the new graphs on the web page now have the correct code beside them.

I'll try to figure out a nice way of generating readable markdown API docs using [documentationjs](http://documentation.js.org/) tomorrow. After that, the fork should be in a releasable state 😊

**Comment by jens-ox** [comment]
Also, according to [BundlePhobia](https://bundlephobia.com/result?p=mg2@0.2.0), the new version is now at ~10kB minified + gzipped, including all D3 dependencies.

**Comment by jens-ox** [comment]
Documentation is done and linked in the README. I also tried to make the code as accessible as possible for new contributions using [CodeClimate](https://codeclimate.com/github/jens-ox/metrics-graphics).

I also [pushed the version on npm](https://www.npmjs.com/package/mg2) and set [a release in GitHub](https://github.com/jens-ox/metrics-graphics/releases/tag/v0.2.2).

I would consider the re-write to now be ready for use.

**Comment by jens-ox** [comment]
@wlach any plans on merging this someday? Otherwise I would ask GitHub to convert the fork to a standalone repo.

**Comment by wlach** [comment]
> @wlach any plans on merging this someday? Otherwise I would ask GitHub to convert the fork to a standalone repo.

Hi @jens-ox! I had a quick look through everything you did-- it really looks great. 

I think my feeling has shifted towards suggesting that maybe you should rebrand your project with a new name and github organization. I think a fresh start would be what's best for essentially a new project as I don't think the issue / PR history on this repo is really relevant anymore. After you've done this, I'd like to archive metricsgraphics and turn the site into a pointer to whatever you produce. What do you think?

**Comment by sandstrom** [comment]
@wlach While there isn't technically much of a difference between a "spiritual successor" and v2, I think that would lose some intangibles tied to the MetricsGraphics.

MetricsGraphics isn't just the code itself, it's also other things:

- The philosophy behind the library, quoting from the website "a simple way to produce common types of graphics in a *principled, consistent* and *responsive* way." One could, of course, create a new library with the same philosophy, but if the old one is being archived, why not continue.

- The website (with all the inbound links) and the name itself. Building awareness for a new library takes time, why not use the things that already exist.

Obviously not up to me though, and also depend on what @jens-ox wants. The two of you should certainly decide!

I'm not saying a fresh start is 100% bad. There are also some benefits, for example a chance to adjust the name (perhaps there is an even better one!) or maybe rethink some things (i.e. easier to do more "breaking changes").

I think the work @jens-ox has done is awesome and it will be great both as a v2 for MetricsGraphics or as a spiritual successor, if that is the path you decide to go down.

**Comment by sandstrom** [comment]
**These comments are about the v2 work, previous post was about the Github org and naming.**

@jens-ox Awesome! It's very impressive to see how fast it's going!

Some thoughts:
- Would it make sense to add data to the readme example?

```js
import LineChart from 'mg2';

let data = [
  [1, 12],
  [2, 5],
  [3, 19],
  [4, 30],
];

new LineChart({
  data, // some array of data objects
  width: 600,
  height: 200,
  target: '#chart',
  area: true,
  xAccessor: 'date',
  yAccessor: 'value'
});
```

- One thing that I would look at when evaluating a charting library, is to understand if it'll be able to cover all the edge cases I'm interested in. For example, can it do multiple lines, y-axis that doesn't start at 0, currency in y-axis, handle missing data, etc. What I really like about MetricsGraphics is that it excel at most of these. I know some things aren't yet implemented in MG2, but perhaps we could increase the number of examples to better showcase what's available in the library, similar to the old examples site (https://metricsgraphicsjs.org/examples.htm#axes).

- I noticed some files had upper/lower case in them. Extremely minor, but perhaps one could use `snake_case` or `dash-erized` casing instead? to keep all file-names lower-case (except e.g. README.md and a few others that are upper-case by convention). This is very subjective though, so I'm not saying this is better, just that I'm used to file names being lower case.

*(These aren't big though, just some thoughts, up to you to decide of course!)*

**Comment by jens-ox** [comment]
> I think my feeling has shifted towards suggesting that maybe you should rebrand your project with a new name and github organization. I think a fresh start would be what's best for essentially a new project as I don't think the issue / PR history on this repo is really relevant anymore. After you've done this, I'd like to archive metricsgraphics and turn the site into a pointer to whatever you produce. What do you think?

Hi @wlach! Thanks for getting back. I prefer the "merging" approach, mostly for the following reasons:
* The API of the new version tries to be as similar as possible to the API of the old version.
* Having the PR and issue history helps deciding what features to implement next.
* I personally making an existing library better than creating yet another one.

**Comment by jens-ox** [comment]
> Would it make sense to add data to the readme example?

Hi @sandstrom! Thanks for your input. Adding data makes sense - I think the best idea would be to link the actual data used for the example graph. I'll add a link to it in the readme.

> [...], but perhaps we could increase the number of examples [...]

Yes, that's true. I'll try adding the remaining examples from metricsgraphicsjs.org that aren't yet on the new page.

> [...], but perhaps one could use `snake_case` or `dash-erized` casing instead?

That makes sense. I've always used camelCase for file names until now, but I'm open to changing that 😊 
Anyone else got input on file naming conventions? The usual resources like [clean-code-javascript](https://github.com/ryanmcdermott/clean-code-javascript) don't seem to have any input on that topic 😅

**Comment by wlach** [comment]
> > I think my feeling has shifted towards suggesting that maybe you should rebrand your project with a new name and github organization. I think a fresh start would be what's best for essentially a new project as I don't think the issue / PR history on this repo is really relevant anymore. After you've done this, I'd like to archive metricsgraphics and turn the site into a pointer to whatever you produce. What do you think?
> 
> Hi @wlach! Thanks for getting back. I prefer the "merging" approach, mostly for the following reasons:
> 
>     * The API of the new version tries to be as similar as possible to the API of the old version.
> 
>     * Having the PR and issue history helps deciding what features to implement next.
> 
>     * I personally prefer making an existing library better than creating yet another one.

Ok! You should now have an invite to be an administrator of the metricsgraphics organization. 🙌 Please feel free to take things forward as you see fit. 😄 

npm doesn't seem to want to allow me to invite new contributors right now (looks like a site error), but I'll set a reminder to try again later today.

Note that the metricsgraphicsjs.org domain is currently owned by Mozilla and deploys via netlify from github pages (same as https://metricsgraphics.github.io/metrics-graphics/). At some point in the near future we'll want to transfer the domain to you if you want to keep it-- this is probably going to be a bit of a bureaucratic pain but I'll try and make it happen. Feel free to reach out to me in a month or so on my private email (`wrlach@gmail.com`) about that.

**Comment by jens-ox** [comment]
> Ok! You should now have an invite to be an administrator of the metricsgraphics organization. 🙌 Please feel free to take things forward as you see fit. 😄

That's great news! I'm feeling quite honored 😊 

My next steps would be:

* re-open this PR for a better overview of the changes
* finish adding the missing examples to the fork
* preparations for merge (name adaptations etc) on the fork
* merge
* push to npm under pre-release flag
* test that everything works (maybe add some e2e tests and add them to CodeClimate)
* bump major version

**Comment by jens-ox** [comment]
Also, I'll start doing some greenkeeping on PRs and issues 👍

**Comment by sandstrom** [comment]
@jens-ox Congrats, a well-deserved honor! 🏅 

## File Names

Regarding file names, its definitely a minor thing. It's safe, but I'd say it's rare. Most will do under_score or dash-case. I think you'll find that ~80% of open-source projects use only lower-case in file names.

https://softwareengineering.stackexchange.com/questions/149411/is-it-safe-to-use-camelcased-file-names

## Issue Gardening

Good idea with issue gardening!

One suggestion is to use the 'canned reply' feature in Github (you probably know already).

Here are some snippets that I often use:

### issue is really a question

> Is this an issue with the code itself, or a general question? For general questions [Stackoverflow](https://stackoverflow.com/) is better than Github.
> 
> I'm closing this now, but I'm willing to reopen if there is an actual code issue. If so, steps to reproduce (and ideally a failing test-case) is a good start.

### feature suggestion that doesn't feel very urgent

> Thanks for thinking about how this project can be improved! Since this code is open-source, without anyone getting paid to work on it, it's difficult to satisfy all the wishes that people may have. I hope you understand! 🌻 
> 
> So if you want something, a good first step is to explain in detail what you think should be changed. If others agree that it's a good idea, the next step would be for you to open a PR with the necessary code changes.
> 
> I'm going to close this issue. But if you want to help out improving this project I'm happy to discuss and give feedback on a proposed change.

I'd basically just close more or less all old issues. Working through them is a lot of work and prioritizing based on issues that may be several years old is rarely ideal. Better that you focus on the things you think are important now.

**Comment by jens-ox** [comment]
Missing points, active points and baselines are added, together with some examples.

The following features are missing:
* data tables
* button layouts
* least squares lines
* brushing and zooming

Some remarks:
- ad 1,2: I think that tables and buttons are out of scope for a data visualization library. Way better solutions exist for both problems.
- ad 3: I think the focus of MetricsGraphics should be on visualization. A least squares line (or any other kind of statistical helper lines) can easily be passed.
- ad 4: I don't really know about that one. Brushing and zooming is nice to have, but hard to get right, especially for mobile. Also, custom domains can be passed, so adding a slider (or something else) is possible.

Does anyone else have something to add to those remarks? Otherwise, I'd start with the merge preparations today.

**Comment by jens-ox** [comment]
The fork is ready to be merged.
@wlach do you have anything to add? Otherwise I would merge 👍

**Comment by wlach** [comment]
> The fork is ready to be merged.
> @wlach do you have anything to add? Otherwise I would merge 👍

Some context on brushing & zooming: this was something we really wanted for some internal tools @ Mozilla (I actually mentored a GSOC project about it a few years back), but I defer to your judgment on whether to keep it -- the internal need has long-since passed. 

I agree on the other items like buttons and data tables, they are occasionally useful for data visualization but IMO the features never reached a level of maturity that I was happy with, and felt kind of out of place.

**Comment by jens-ox** [comment]
Hi @wlach, thanks for getting back!
I tried adding brushing, it wasn't as bad as I thought. So brushing is now included 😊 
I also updated the examples to include brushing (always the first one).

**Comment by sandstrom** [comment]
Awesome to see this merged! 🎉 🎆 

Regarding your questions:

- data tables => Agree, out of scope
- button layouts => Agree, out of scope
- least squares lines => Agree its not a necessity, but could be useful
- brushing and zooming => Agree, hard on mobile, but saw your next comment that you did implement it

***

More broadly, I think it's important for a library to have fairly strict boundaries on what it's trying to do, and what stuff is out of scope. Also, every new feature has a "maintenance cost" so another reason to not add too much.

For me, what MetricsGraphics does really well is that the graphs are presented beautifully and simply, i.e. the focus on great visual representation of data. The type of visualization that you'll find in good newspapers such as New York Times or [The Economist](https://www.google.com/search?q=economist+graphs&source=lnms&tbm=isch&sa=X). 

For this, some advanced features are needed. Things like annotations, support for missing data, confidence bands, log scale, time spans and time formatting. But it shouldn't try to compete with Mathlab or other advanced visualization software.

These are just my thoughts though, you're the steward here!

**Pull request merged**
