### PR TITLE
Translate metrics-graphics to TypeScript

### PR DESCRIPTION
**Pull request by jens-ox**
This PR translates MetricsGraphics to TypeScript, so using mg in a TypeScript project should go smoothly (typings etc).

@wlach I wrote you a mail once regarding the push rights for npm, could you give them to me?

### CODE REVIEW

**Comment by wlach** [comment]
> This PR translates MetricsGraphics to TypeScript, so using mg in a TypeScript project should go smoothly (typings etc).
> 
> @wlach I wrote you a mail once regarding the push rights for npm, could you give them to me?

@jens-ox Of course! I assume it's @jens-ox on npm as well? https://www.npmjs.com/~jens-ox

**Comment by jens-ox** [comment]
Yes, that's me :relaxed:

**Comment by wlach** [comment]
Ok! You are now an admin of the package. 😄

**Comment by jens-ox** [comment]
Great, thanks! Will publish the first 3.x version in a sec :relaxed:

**Pull request merged**
