### PR TITLE
Don't render duplicate ticks on graphs (fixes #848)

### LINKED ISSUE #848: Some data causes x-axis to show year multiple times
## Steps to reproduce

Load [this JSFiddle](https://jsfiddle.net/jrp7fdkk/11/), which renders the following data:

```javascript
[
    { x: new Date('2017-01-01'), y: 0 },
    { x: new Date('2019-01-01'), y: 10 },
]
```

### PR DESCRIPTION
**Pull request by wlach**

### CODE REVIEW

**Comment by wlach** [comment]
@hamilton Could you have a look at this? Mostly just cleanup, not necessarily optimal but it does unblock a problem that our datatools team is having.

**Comment by openjck** [comment]
I don't think I'm familiar enough with the codebase to provide any useful feedback on the code itself, but I wanted to say that this does fix the issue we were seeing. :smiley:

**Comment by hamilton** [comment]
Hello! Will take a look this weekend.

**Comment by wlach** [comment]
Ok, spent more time on this. In the end, I decided that *lowering* the thresholds is actually what I needed to do. That, combined with using the distance between ticks as the determiner of whether to show a tick label, seems to give nice results in the example page:

image

**Comment by hamilton** [comment]
Yeah, this looks great! One thing I'm wondering about. For the "Less Than A Minute" graphs, it appears that we're also including ms in the display now:

screen shot 2018-05-20 at 10 24 33 am

Which I don't think adds anything to the understanding (compared to what's in master right now):

screen shot 2018-05-20 at 10 24 38 am

Could we remove the ms piece from the "less than a minute" display? Perhaps we need to also come up with a "less than a second" one as well, which may be useful for some types of displays, but we could tackle that in another PR.

**Comment by wlach** [comment]
Ah, I needed to update the "less than a second" threshold to actually be less than a second, now that we're using the distance between ticks to decide on what to display. Fixed now, examples look good, gonna merge. :)

**Comment by hamilton** [comment]
Great work! Such a nice improvement.

**Pull request merged**
