### PR TITLE
Add option to set how line(s) are dashed programmatically

### PR DESCRIPTION
**Pull request by thomaschampagne**
In the same way that the "colors" array attribute, this PR allows to set programmatically how lines are dashed using **stroke-dasharray** css property.

This PR includes **code + documentation**. Here the result:

image

Why this PR? Like my previous PRs, the need comes from my sport app [Elevate (formerly stravistix)](https://thomaschampagne.github.io/elevate/). 

The app integrates a feature called "Year progressions" where an athlete can track his progress over the year and compare with previous years (e.g. distance). 

**The need is:** Allowing athlete to set a **distance target dashed line** (e.g. 4500km) 
to make sure that he follows this line as closely as possible throughout the year to fulfill his objective. Something like that:

untitled

This cannot be covered by overriding **.mg-lineX-color** classes because number of lines to handle is "dynamic" (=unknown number of years at runtime)

Thanks !

### CODE REVIEW

**Comment by wlach** [comment]
This looks great. I'm currently in the process of a big build system refactor (see #907), but I'll look into merging this immediately after that's done.

**Comment by thomaschampagne** [comment]
@wlach Just to know do you have any status on the #907 completion?

**Comment by wlach** [comment]
> @wlach Just to know do you have any status on the #907 completion?

Sorry for the delay. I've spent another 10 hours or so working on it, but it's a large task and I don't have a lot of extra time these days. Hope to have it done within the next couple months.

**Comment by thomaschampagne** [comment]
@jens-ox Can we say that PR is now deprecated/dead and can be closed?

_(Still looking forward the next metric-graphics with typescript (and retro-compatibility old version? for 
 my project using it https://twitter.com/champagnethomas/status/1197846249061408769)_

**Comment by jens-ox** [comment]
Hi @thomaschampagne! I'll look into it tomorrow. I had to pause working on OSS due to some Covid-related changes in work, but I'm back now ☺️

Yeah, the PRs are pretty much all deprecated, but I didn't want to close them in order to track what could be improved in the future.

I started working on a Typescript port some days ago, see the related branch.

I'll also talk to @wlach concerning publish rights for npm, so that I can deploy a new major version.

Concerning the backward-compatibility with the old interface: I believe that it would be best to put that into a separate wrapper to keep the codebase clean. I wanted to work on wrappers for the popular frameworks/libs anyway, so this would be a good candidate for a first wrapper ☺️

**Pull request closed without merging**
